# GitHub Actions Workflow: Deploy Static Files to VPS

name: Deploy Static Site

# Trigger this workflow on every push to the 'main' branch
on:
  push:
    branches:
      - main

jobs:
  deploy:
    # Use the latest Ubuntu runner
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the repository code
      - name: Checkout Code
        uses: actions/checkout@v4

      # 2. Deploy files to the server
      # Uses the 'scp' (Secure Copy) protocol to transfer the application files
      - name: Deploy to Server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          source: "App.tsx,components,index.html,index.tsx,metadata.json,types.ts"
          target: "/var/www/www-root/data/www/app.bean.st"
